name: game_of_generals
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: Force Commander
      fonts:
        - asset: lib/assets/fonts/forcecommanderexpand.ttf

    - family: Eurostile
      fonts:
        - asset: lib/assets/fonts/Eurostile.ttf

    - family: Eurostile Bold
      fonts:
        - asset: lib/assets/fonts/Eurostile-Bold Regular.ttf
